import subprocess
import os

OUTPUT_MD = "/mnt/c/Users/USER/.gemini/antigravity-ide/brain/98631cef-9cf8-4fa6-a29d-0f1b753c4b36/netflow_statistical_analysis.md"
DATA_DIR = "/mnt/g/ARPA47_NetFlow_Anonymized"

def run_query(query_args, title, description):
    print(f"Running query: {title}...")
    cmd = ["nfdump", "-R", DATA_DIR] + query_args
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        # Clean up output a bit
        lines = result.stdout.strip().split('\n')
        # Format as markdown block
        md = f"## {title}\n\n{description}\n\n```text\n"
        for line in lines:
            if "wsl: Failed to start the systemd user session" in line:
                continue
            md += line + "\n"
        md += "```\n\n"
        return md
    except subprocess.CalledProcessError as e:
        return f"## {title}\n\n**Error running query:**\n```text\n{e.stderr}\n```\n\n"

def main():
    print("Starting deep statistical analysis of the 60GB NetFlow dataset...")
    
    with open("/mnt/d/Development/ARPA47/report.md", "w") as f:
        f.write("# ARPA47 NetFlow Dataset: Comprehensive Statistical Analysis\n\n")
        f.write("This report was generated by querying the complete 32-day, 4000-subscriber anonymized NetFlow dataset.\n\n")
        f.write("---\n\n")
        
    queries = [
        (["-I"], 
         "1. Overall Dataset Summary", 
         "High-level overview of total flows, packets, and bytes across the entire 32-day period, broken down by TCP, UDP, and ICMP."),
        
        (["-s", "srcport/bytes", "-n", "20"], 
         "2. Top 20 Source Ports (Download Traffic & Services)", 
         "Source ports primarily represent the services that users are downloading from. For example, high traffic from port 443 indicates massive HTTPS/QUIC downloads from CDNs."),
        
        (["-s", "dstport/bytes", "-n", "20"], 
         "3. Top 20 Destination Ports (User Activity & Uploads)", 
         "Destination ports represent what users are explicitly connecting to. Port 443 here represents upload requests to web servers, while ephemeral high ports represent P2P, gaming, or VoIP."),
        
        (["-s", "ip/bytes", "-n", "20"], 
         "4. Top 20 IPs by Volume (Top Talkers / CDNs)", 
         "The most active IPs in the dataset. External IPs here are likely major CDN nodes (Google, Cloudflare, Meta) or heavily seeded torrent peers."),
         
        (["-s", "record/bytes", "-n", "20"], 
         "5. Top 20 Individual Flow Records", 
         "The single largest continuous connections made during the 32 days. These could be massive OS updates, game downloads, or potential anomalies.")
    ]
    
    for args, title, desc in queries:
        output = run_query(args, title, desc)
        with open("/mnt/d/Development/ARPA47/report.md", "a") as f:
            f.write(output)
            
    print("Analysis complete! Report saved to D:/Development/ARPA47/report.md")

if __name__ == "__main__":
    main()
